version: "3.7"
services:
  traefik:
      container_name: traefik
      image: traefik:v2.2
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./config:/root/.config
          - /var/run/docker.sock:/var/run/docker.sock:ro
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"

        - "traefik.http.routers.traefik_http.rule=Host(`${TRAEFIK_UI_URL}`)"
        - "traefik.http.routers.traefik_http.entrypoints=web"
        - "traefik.http.routers.traefik_http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

        - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_UI_URL}`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.tls=true"
      networks:
          - traefik
  
  wordpress:
    image: wordpress
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # Connect WordPrerss to the database
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: changeme
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      # save the content of WordPress an enable local modifications
      - ./wordpress/data:/var/www/html
    networks:
      - traefik
      - backend
    depends_on:
        - db
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.wp_http.rule=Host(`${WP_URL}`)"
      - "traefik.http.routers.wp_http.entrypoints=web"
      - "traefik.http.routers.wp_http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.http.routers.wp.rule=Host(`${WP_URL}`)"
      - "traefik.http.routers.wp.entrypoints=websecure"
      - "traefik.http.routers.wp.tls=true"

  db:
    # this is the database used by Wordpress
    image: mysql:5.7
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # Connect WordPrerss to the database
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: changeme
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      # Persist the database on disk
      - ./db:/var/lib/mysql
    networks:
      - backend

  nextcloud_database:
      image: mariadb
      container_name: nextcloud_database
      restart: unless-stopped
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - backend
        - traefik
      volumes:
        - db:/var/lib/mysql

  nextcloud:
    depends_on:
      - nextcloud_database
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    environment:
      - MYSQL_HOST=nextcloud_database
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend
      - traefik
    volumes:
      - html:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.nextcloud_http.rule=Host(`${NEXTCLOUD_URL}`)"
      - "traefik.http.routers.nextcloud_http.entrypoints=web"
      - "traefik.http.routers.nextcloud_http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.http.routers.nextcloud.entrypoints=web,websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_URL}`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls=true"

volumes:
  db:
  html:

networks:
  # enable connection with Traefik
  traefik:
    external: true
  # network for the app
  backend:
