[serversTransport]
insecureSkipVerify = true

[entryPoints]

[entryPoints.web]
address = ":80"

[entryPoints.websecure]
address = ":443"

[providers]

[providers.docker]
watch = true
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[api]
dashboard = true
debug = true

[log]
level = "DEBUG"

[accesslog]

[providers.file]
  filename = "/root/.config/ssl.toml"

